#Testando users

GET http://localhost:3333/classes?week_day=1&subject=Matemática&time=11:00

###
GET http://localhost:3333/schedule

###

POST http://localhost:3333/classes
Content-Type: application/json

{
    "name":"Luiz Carlos",
    "avatar": "https://avatars3.githubusercontent.com/u/57350762?s=460&u=5c28607a6573c3f9ae703ebc9e23c31c916e3ab3&v=4",
    "whatsapp": "991890441",
    "bio": "Programador júnior e discente no IFAL",

    "subject": "Matemática",
    "cost": 80,
    "schedule": [
        { "week_day": 1, "from": "8:00", "to": "12:00" },
        { "week_day": 3, "from": "10:00", "to": "18:00" },
        { "week_day": 4, "from": "8:00", "to": "12:00" }
    ]
}

###
POST http://localhost:3333/connections
Content-Type: application/json

{
    "user_id": 1
}

###

GET http://localhost:3333/connections